
package agh.soa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IParkingService", targetNamespace = "http://soap.soa.agh/")
@SOAPBinding(style = SOAPBinding.Style.RPC)

public interface IParkingService {


    /**
     * 
     * @param parkingPlace
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean freePlace(
        @WebParam(name = "parkingPlace", partName = "parkingPlace")
        ParkingPlace parkingPlace);

    /**
     * 
     * @param parkingPlace
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean takePlace(
        @WebParam(name = "parkingPlace", partName = "parkingPlace")
        ParkingPlace parkingPlace);

}
