
package agh.soa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IParkingService", targetNamespace = "http://soapController.soa.agh/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IParkingService {


    /**
     * 
     * @param parkingPlaceID
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean freePlace(
        @WebParam(name = "parkingPlaceID", partName = "parkingPlaceID")
        int parkingPlaceID);

    /**
     * 
     * @param parkingPlaceID
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean takePlace(
        @WebParam(name = "parkingPlaceID", partName = "parkingPlaceID")
        int parkingPlaceID);

}
