
package agh.soa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IParkingService", targetNamespace = "http://soa.agh/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IParkingService {


    /**
     * 
     * @param parkingPlace
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soa.agh/IParkingService/isEmptyRequest", output = "http://soa.agh/IParkingService/isEmptyResponse")
    public boolean isEmpty(
        @WebParam(name = "parkingPlace", partName = "parkingPlace")
        ParkingPlace parkingPlace);

    /**
     * 
     * @param parkingPlace
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soa.agh/IParkingService/freePlaceRequest", output = "http://soa.agh/IParkingService/freePlaceResponse")
    public boolean freePlace(
        @WebParam(name = "parkingPlace", partName = "parkingPlace")
        ParkingPlace parkingPlace);

    /**
     * 
     * @param parkingPlace
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soa.agh/IParkingService/takePlaceRequest", output = "http://soa.agh/IParkingService/takePlaceResponse")
    public boolean takePlace(
        @WebParam(name = "parkingPlace", partName = "parkingPlace")
        ParkingPlace parkingPlace);

}
