
package agh.soa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ParkingServiceImplService", targetNamespace = "http://soapController.soa.agh/", wsdlLocation = "http://localhost:8080/implementation-1.0-SNAPSHOT/ParkingServiceImpl?wsdl")
public class ParkingServiceImplService
    extends Service
{

    private final static URL PARKINGSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PARKINGSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PARKINGSERVICEIMPLSERVICE_QNAME = new QName("http://soapController.soa.agh/", "ParkingServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/implementation-1.0-SNAPSHOT/ParkingServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PARKINGSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PARKINGSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ParkingServiceImplService() {
        super(__getWsdlLocation(), PARKINGSERVICEIMPLSERVICE_QNAME);
    }

    public ParkingServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PARKINGSERVICEIMPLSERVICE_QNAME, features);
    }

    public ParkingServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, PARKINGSERVICEIMPLSERVICE_QNAME);
    }

    public ParkingServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PARKINGSERVICEIMPLSERVICE_QNAME, features);
    }

    public ParkingServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ParkingServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IParkingService
     */
    @WebEndpoint(name = "ParkingServiceImplPort")
    public IParkingService getParkingServiceImplPort() {
        return super.getPort(new QName("http://soapController.soa.agh/", "ParkingServiceImplPort"), IParkingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IParkingService
     */
    @WebEndpoint(name = "ParkingServiceImplPort")
    public IParkingService getParkingServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soapController.soa.agh/", "ParkingServiceImplPort"), IParkingService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PARKINGSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw PARKINGSERVICEIMPLSERVICE_EXCEPTION;
        }
        return PARKINGSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
